name: Deploy Preview

on:
  push:
    branches:
      - poultry
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set and Output Environment Variables
        run: |
          export PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}"
          export MINI_APP_ID="${{ secrets.MINI_APP_ID }}"
          export COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "PRIVATE_KEY: $PRIVATE_KEY"
          echo "MINI_APP_ID: $MINI_APP_ID"
          export PRIVATE_KEY_PATH="/path/to/${{ secrets.PRIVATE_KEY }}"
          echo "PRIVATE_KEY_PATH: $PRIVATE_KEY_PATH"
      - name: Create private key file
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ./private.key
          echo "Private key file created!"
          ls -l  # 可选的，用于验证文件是否创建成功
      - name: Use private key file
        run: |
          pwd

        
