name: Deploy Preview

on:
  push:
    branches:
      - poultry
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:mp-weixin

      - name: actions.mini-program
        uses: actions.mini-program@main
        with:
          project_type: miniProgram
          action_type: preview
          project_path: ./dist/build/mp-weixin
          version: 1.0.0
          command_options:
            --enable-es5
            # --project-ignores=['node_modules/**/*']
        env:
          MINI_APP_ID: ${{ secrets.MINI_APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
