name: Deploy Preview

on:
  push:
    branches:
      - poultry
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:mp-weixin

      - name: Upload
        uses: crazyurus/miniprogram-action@1.0.0
        with:
          action_type: upload
          version: ${{ github.ref_name }}
          project_path: ./dist/build/mp-weixin/
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
