name: Deploy Preview

on:
  push:
    branches:
      - poultry
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install pnpm -g

      - name: Install dependencies2 
        run: pnpm install

      - name: Build
        run: pnpm run build:mp-weixin

      - name: Set Environment Variables
        run: |
          export PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}"
          export MINI_APP_ID="${{ secrets.MINI_APP_ID }}"
          export COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
      - name: Upload Mini Program
        run: |
          npm install miniprogram-ci -g
          miniprogram-ci upload --pp ./dist/build/mp-weixin --pkp $PRIVATE_KEY --appid $MINI_APP_ID --version 1.0.0 --enable-es6 true --uv  $COMMIT_MESSAGE
