name: Deploy Preview

on:
  push:
    branches:
      - poultry
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:mp-weixin

      - name: actions.mini-program
        uses: echoings/actions.mini-program@0.0.3
        with:
          project_type: miniProgram
          action_type: upload
          project_path: ./dist/build/mp-weixin
          version: 1.0.0
          remark: ${{ github.event.head_commit.message }}
          # 开启es6编译成es5
          command_options:
            --enable-es6
            --enable-es7
            --enable-condition
            --enable-enhance
            # --project-ignores=['node_modules/**/*']
        env:
          MINI_APP_ID: ${{ secrets.MINI_APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
